name: Tailscale Setup with assumed 655GB SSD

on:
  workflow_dispatch:

jobs:
  tailscale-setup:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download and silently install Tailscale
      shell: pwsh
      run: |
        $installer = "$env:TEMP\tailscale-install.exe"
        Invoke-WebRequest -Uri "https://pkgs.tailscale.com/stable/tailscale-ipn-setup.exe" -OutFile $installer
        Start-Process -FilePath $installer -ArgumentList '/quiet' -Wait

    - name: Connect to Tailscale using auth key
      env:
        TAILSCALE_AUTH_KEY: ${{ secrets.TAILSCALE_AUTH_KEY }}
      shell: pwsh
      run: |
        $tailscalePath = "C:\Program Files (x86)\Tailscale IPN\tailscale.exe"
        & $tailscalePath up --auth-key=$env:TAILSCALE_AUTH_KEY | Out-Null

        $status = & $tailscalePath status | Out-String
        $ipLine = $status -split "`n" | Where-Object { $_ -match '100\.' } | Select-Object -First 1
        if ($ipLine) {
          $ip = ($ipLine -split '\s+')[0]
          Write-Host "Connected Tailscale IP: $ip"
        } else {
          Write-Warning "Could not determine Tailscale IP"
        }

    - name: Display completion info
      shell: pwsh
      run: |
        Write-Host "==============================="
        Write-Host "Tailscale VPN setup complete ✅"
        Write-Host "Assuming you have at least 655GB SSD available on the machine."
        Write-Host "Your Tailscale IP is shown above."
        Write-Host "Keep your auth key secure using GitHub Secrets."
        Write-Host "==============================="
        
