name: Robust Tailscale Install with MSI on Windows Server

on:
  workflow_dispatch:

jobs:
  tailscale-msi-install:
    runs-on: windows-2022

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Download Tailscale MSI installer with retries
      shell: pwsh
      run: |
        $url = "https://pkgs.tailscale.com/stable/tailscale-ipn-setup.msi"
        $output = "$env:TEMP\tailscale-setup.msi"
        $maxRetries = 3
        $tryCount = 0
        do {
          try {
            Invoke-WebRequest -Uri $url -OutFile $output -TimeoutSec 30 -ErrorAction Stop
            Write-Host "Downloaded Tailscale MSI successfully"
            break
          } catch {
            $tryCount++
            Start-Sleep -Seconds 5
            if ($tryCount -ge $maxRetries) {
              throw "Failed to download MSI installer after $maxRetries attempts."
            }
          }
        } while ($true)

    - name: Install Tailscale MSI silently with logging
      shell: pwsh
      run: |
        $msiPath = "$env:TEMP\tailscale-setup.msi"
        $logPath = "$env:TEMP\tailscale-install.log"
        $install = Start-Process msiexec.exe -ArgumentList "/i", $msiPath, "/qn", "/l*v", $logPath -Wait -PassThru
        if ($install.ExitCode -ne 0) {
          Write-Error "MSI Installer failed with exit code $($install.ExitCode)."
          Write-Host "Check log at $logPath for details."
          throw "Installation failed"
        }
        Write-Host "Tailscale installed successfully."

    - name: Connect to Tailscale using auth key
      env:
        TAILSCALE_AUTH_KEY: ${{ secrets.TAILSCALE_AUTH_KEY }}
      shell: pwsh
      run: |
        $tailscalePath = "C:\Program Files (x86)\Tailscale IPN\tailscale.exe"
        & $tailscalePath up --auth-key=$env:TAILSCALE_AUTH_KEY | Out-Null
        $status = & $tailscalePath status | Out-String
        $ipLine = $status -split "`n" | Where-Object { $_ -match '100\.' } | Select-Object -First 1
        if ($ipLine) {
          $ip = ($ipLine -split '\s+')[0]
          Write-Host "Connected Tailscale IP: $ip"
        } else {
          Write-Warning "Could not determine Tailscale IP"
        }

    - name: Display final info
      shell: pwsh
      run: |
        Write-Host "==============================="
        Write-Host "Tailscale setup complete!"
        Write-Host "Check logs for install details if any errors occurred."
        Write-Host "Keep your auth key secure."
        Write-Host "==============================="
        
