name: Tailscale Setup with 16GB RAM and SSD Check

on:
  workflow_dispatch:

jobs:
  setup-tailscale:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Check RAM and SSD with 16GB RAM minimum
      shell: pwsh
      run: |
        $requiredRAMGB = 16
        $requiredSSDGB = 200  # prag spațiu liber SSD, modificabil
        $ramGB = [math]::round((Get-CimInstance -ClassName Win32_ComputerSystem).TotalPhysicalMemory / 1GB, 2)
        $freeSpaceGB = ([math]::round((Get-PSDrive -Name C).Free / 1GB, 2))

        if ($ramGB -lt $requiredRAMGB) {
          Write-Warning "Warning: RAM under $requiredRAMGB GB detected: $ramGB GB"
        } else {
          Write-Host "RAM OK: $ramGB GB"
        }

        if ($freeSpaceGB -lt $requiredSSDGB) {
          Write-Warning "Warning: SSD space under $requiredSSDGB GB detected: $freeSpaceGB GB"
        } else {
          Write-Host "SSD OK: $freeSpaceGB GB"
        }

    - name: Download and install Tailscale silently
      shell: pwsh
      run: |
        $installer = "$env:TEMP\tailscale-setup.exe"
        Invoke-WebRequest -Uri "https://pkgs.tailscale.com/stable/tailscale-ipn-setup.exe" -OutFile $installer
        Start-Process -FilePath $installer -ArgumentList '/quiet' -Wait

    - name: Connect to Tailscale with auth key
      env:
        TAILSCALE_AUTH_KEY: ${{ secrets.TAILSCALE_AUTH_KEY }}
      shell: pwsh
      run: |
        $tailscaleExe = "C:\Program Files (x86)\Tailscale IPN\tailscale.exe"
        & $tailscaleExe up --auth-key=$env:TAILSCALE_AUTH_KEY | Out-Null
        
        $status = & $tailscaleExe status | Out-String
        $ipLine = $status -split "`n" | Where-Object { $_ -match '100\.' } | Select-Object -First 1
        if ($ipLine) {
          $ip = ($ipLine -split '\s+')
          Write-Host "Connected Tailscale IP: $ip"
        } else {
          Write-Warning "Could not determine Tailscale IP"
        }
        Write-Host "Auth Key used (hidden for security): ***"

    - name: Show useful connection info
      shell: pwsh
      run: |
        Write-Host "==============================="
        Write-Host "Tailscale VPN setup complete ✅"
        Write-Host "Your Tailscale IP is displayed above."
        Write
        
